# eSimMate User Configuration File

logging:
  level: "INFO"
  file_enabled: true
  console_enabled: true

package_managers:
  preferred_linux: "apt"
  preferred_windows: "winget"

search_paths:
  kicad: []
  ngspice: []
